get:
  tags:
    - Product
  summary: Get a list of Products
  description: Get a list of all products
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product_list.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/Problem.yaml
post:
  tags:
    - Product
  summary: create a product
  description: create a new product
  operationId: createProduct
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/v1/product.yaml
  responses:
    '201':
      description: Created
      headers:
        Location:
          description: Location of the new resource
          schema:
            type: string
            example: /v1/products/uuid
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/Problem.yaml